# Generated by Django 3.0.2 on 2020-01-09 04:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Activity')),
                ('grade_range', models.CharField(max_length=50, verbose_name='What grade range is this activity suitable for?')),
                ('description', models.TextField(max_length=300, verbose_name='Enter a short description about the activity')),
                ('runnable', models.BooleanField(default=True, verbose_name='Is this activity runnable?')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
            managers=[
                ('runnable_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Note: ')),
                ('date_added', models.DateTimeField()),
                ('weekday', models.BooleanField(verbose_name='Would you like to show this note during the weekdays?')),
                ('weekend', models.BooleanField(verbose_name='Would you like to show this note during the weekends?')),
                ('show', models.BooleanField(default=True, verbose_name='Do you want to show this note right away?')),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='How important is this note on a scale of 1-6?')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
            managers=[
                ('weekday_notes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeekendActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_decided', models.DateField(verbose_name='When were the weekend activities decided?')),
                ('Backstage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Backstage', to='design_lab.Activities')),
                ('Sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sandbox', to='design_lab.Activities')),
                ('Studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studio', to='design_lab.Activities')),
                ('Treehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treehouse', to='design_lab.Activities')),
            ],
            options={
                'verbose_name_plural': 'Weekend Activities',
            },
            managers=[
                ('to_run', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.CharField(max_length=100, null=True, verbose_name='Grade Range')),
                ('total_numbers', models.IntegerField(verbose_name='Total Group Numbers')),
                ('current_date', models.DateField()),
                ('backstage_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backstage', to='design_lab.Activities')),
                ('sandbox_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox', to='design_lab.Activities')),
                ('studio_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='design_lab.Activities')),
                ('treehouse_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treehouse', to='design_lab.Activities')),
            ],
            options={
                'verbose_name_plural': 'Museum Group Visitation',
            },
            managers=[
                ('monday_to_today', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.CharField(choices=[('Unrunnable', 'Unrunnable'), ('Runnable', 'Runnable'), ('Removed', 'Removed')], max_length=15, verbose_name='What change are you making to this activity?')),
                ('description', models.CharField(max_length=200)),
                ('date_changed', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_lab.Activities')),
            ],
        ),
    ]
