# Generated by Django 3.0.2 on 2020-01-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_lab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekendActivities',
        ),
    ]
