# Generated by Django 3.0.2 on 2020-01-09 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('design_lab', '0002_delete_weekendactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_decided', models.DateField(verbose_name='When were the weekend activities decided?')),
                ('Backstage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Backstage', to='design_lab.Activities')),
                ('Sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sandbox', to='design_lab.Activities')),
                ('Studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studio', to='design_lab.Activities')),
                ('Treehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treehouse', to='design_lab.Activities')),
            ],
            options={
                'verbose_name_plural': 'Weekend Activities',
            },
            managers=[
                ('to_run', django.db.models.manager.Manager()),
            ],
        ),
    ]
