# Generated by Django 3.0.2 on 2020-01-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_lab', '0005_auto_20200109_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekend',
            name='Backstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Backstage', to='design_lab.Activities'),
        ),
        migrations.AlterField(
            model_name='weekend',
            name='Sandbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sandbox', to='design_lab.Activities'),
        ),
        migrations.AlterField(
            model_name='weekend',
            name='Studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Studio', to='design_lab.Activities'),
        ),
        migrations.AlterField(
            model_name='weekend',
            name='Treehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treehouse', to='design_lab.Activities'),
        ),
    ]
