# Generated by Django 3.0.2 on 2020-01-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_lab', '0006_auto_20200109_2106'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='weekend',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='description',
        ),
    ]
